//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreClone.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<int> SoTienTra { get; set; }
        public int MaKH { get; set; }
        public int MaND { get; set; }
    }
}
