//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreClone.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public int MaSach { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string TenSach { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
    }
}
